name: 'vcpkg environment'
description: 'Activate vcpkg environment'
author: 'Jonatan Antoni <jonatan.antoni@arm.com'

inputs:
  config:
    description: "Path to vcpkg-configuration.json"
    required: false
    default: "./vcpkg-configuration.json"
  vcpkg-root:
    description: "Root folder for vcpkg"
    default: "${{ github.workspace }}/.vcpkg"
    required: false
  cache:
    description: "Cache key suffix, set to empty to disable cache."
    default: "-"
    required: false
  
runs:
  using: 'composite'
  steps:
    - name: Cache vcpkg
      uses: actions/cache@v4
      if: ${{ inputs.cache }}
      with:
        key: vcpkg-${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}${{ inputs.cache }}
        restore-keys: |
          vcpkg-${{ runner.os }}-${{ runner.arch }}-
        path: ${{ inputs.vcpkg-root }}

    - name: Set up vcpkg environment windows
      if: runner.os == 'Windows'
      shell: pwsh
      env: 
        VCPKG_ROOT: ${{ inputs.vcpkg-root }}
      run: |
        Write-Host "VCPKG_ROOT=${{ inputs.vcpkg-root }}"
        if (Test-Path "$env:VCPKG_ROOT\vcpkg-init") {
          . "$env:VCPKG_ROOT\vcpkg-init"
        } else {
          iex ((New-Object System.Net.WebClient).DownloadString('https://aka.ms/vcpkg-init.ps1'))
        }
        # vcpkg x-update-registry --all
        # cd (Split-Path -Path ${{ inputs.config }} -Parent)
        # vcpkg activate --json=env.json
        # Write-Host "Preserving vcpkg PATH ..."
        # (Get-Content env.json | ConvertFrom-Json).paths.PATH | ForEach-Object { $_.Trim('"') } | ForEach-Object { Write-Host $_; $env:Path += ";$_" }
        # Write-Host "Preserving vcpkg ENV ..."
        # (Get-Content env.json | ConvertFrom-Json).tools | ForEach-Object { $_.GetEnumerator() } | ForEach-Object { Write-Host "$($Key)=$($Value)"; $env:($Key) = $Value }
        # Remove-Item env.json

    - name: Set up vcpkg environment for linux or macOS
      if: runner.os != 'Windows'
      shell: bash
      env: 
        VCPKG_ROOT: ${{ inputs.vcpkg-root }}
      run: |
        echo "VCPKG_ROOT=${{ inputs.vcpkg-root }}" >> $GITHUB_ENV
        if [ -f "$VCPKG_ROOT/vcpkg-init" ]; then
          . "$VCPKG_ROOT/vcpkg-init"
        else
          . <(curl https://aka.ms/vcpkg-init.sh -L)
        fi

    - name: set vcpkg
      shell: bash
      env: 
        VCPKG_ROOT: ${{ inputs.vcpkg-root }}
      run: |
        vcpkg x-update-registry --all
        cd $(dirname "${{ inputs.config }}")
        vcpkg activate --json=env.json
        echo "Preserving vcpkg PATH ..."
        jq '.paths.PATH[]' env.json | tr -d '\"' >> $GITHUB_PATH
        echo "Preserving vcpkg ENV ..."
        jq '.tools | to_entries | map("\(.key)=\(.value)")[]' env.json | tr -d '\"' >> $GITHUB_ENV
        rm env.json
